### PR TITLE
Fix Windows 8.1 Build

### PR DESCRIPTION
**Pull request by agnat**
This PR collects changes needed to compile mdns on Windows 8.1. It's related to #113.

### CODE REVIEW

**Comment by agnat** [comment]
@essingh, could you try this branch? Just run `node-gyp rebuild --verbose` in the root directory and gist the result.

**Comment by essingh** [comment]
Ok I removed the manually moved libs and exec node-gyp rebuild --verbose on this branch. Here's the [output](https://gist.github.com/essingh/89a6a0aba50703947729)

**Comment by agnat** [comment]
hmk... bummer. I think I need to find me a windows 8.1 box. Let me make a few phone calls. I still think we are really close, though. All we need to do is to point the compiler to the right C(++) runtime lib. I just don't know how to do that from the top of my head. Sorry about that... :-/

**Comment by essingh** [comment]
No worries man. I appreciate you taking the time to help out (let alone
making the module itself). Our project is primarily focused on the OS X
platform.. Hopefully by the time we switch gears and start to focus on the
Win version, mdns will be further along on Win 8.1. Thanks again.

**Comment by mathiask88** [comment]
I tried ```master``` on Win 8.1 x64 VS13 Update 4 Bonjour SDK 2.0.4.0 and everything worked fine.
cmd output:
```
C:\Users\Mathias\Documents\GitHub\node_mdns>npm install

> mdns@2.2.2 install C:\Users\Mathias\Documents\GitHub\node_mdns
> node-gyp rebuild


C:\Users\Mathias\Documents\GitHub\node_mdns>node "C:\Program Files\nodejs\node_m
odules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuil
d
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parall
ele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  dns_sd.cpp
  dns_service_browse.cpp
  dns_service_enumerate_domains.cpp
  dns_service_get_addr_info.cpp
  dns_service_process_result.cpp
  dns_service_ref.cpp
  dns_service_ref_deallocate.cpp
  dns_service_ref_sock_fd.cpp
  dns_service_register.cpp
  dns_service_resolve.cpp
  mdns_utils.cpp
  network_interface.cpp
..\src\dns_service_register.cpp(123): warning C4267: '=': Konvertierung von 'si
ze_t' nach 'uint16_t', Datenverlust möglich [C:\Users\Mathias\Documents\GitHub\
node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_ref_sock_fd.cpp) [C
:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_ref_deallocate.cpp)
 [C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\mdns_utils.cpp) [C:\Users\Mathi
as\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_enumerate_domains.c
pp) [C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(184): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_ref.cpp) [C:\Users\
Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(184): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::FunctionTemplate> v8::Per
sistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)" (..\src\d
ns_service_ref.cpp) [C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_b
indings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_resolve.cpp) [C:\Us
ers\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_process_result.cpp)
 [C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_browse.cpp) [C:\Use
rs\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_sd.cpp) [C:\Users\Mathias\D
ocuments\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_get_addr_info.cpp)
[C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\dns_service_register.cpp) [C:\U
sers\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\network_interface.cpp) [C:\User
s\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
  txt_record_ref.cpp
  txt_record_create.cpp
  txt_record_deallocate.cpp
  txt_record_set_value.cpp
  txt_record_get_length.cpp
  txt_record_buffer_to_object.cpp
..\src\txt_record_set_value.cpp(45): warning C4267: 'Argument': Konvertierung v
on 'size_t' nach 'uint8_t', Datenverlust möglich [C:\Users\Mathias\Documents\Gi
tHub\node_mdns\build\dns_sd_bindings.vcxproj]
..\src\txt_record_create.cpp(30): warning C4267: '=': Konvertierung von 'size_t
' nach 'uint16_t', Datenverlust möglich [C:\Users\Mathias\Documents\GitHub\node
_mdns\build\dns_sd_bindings.vcxproj]
..\src\txt_record_buffer_to_object.cpp(29): warning C4267: 'Argument': Konverti
erung von 'size_t' nach 'uint16_t', Datenverlust möglich [C:\Users\Mathias\Docu
ments\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
..\src\txt_record_buffer_to_object.cpp(36): warning C4267: 'Argument': Konverti
erung von 'size_t' nach 'uint16_t', Datenverlust möglich [C:\Users\Mathias\Docu
ments\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(694): war
ning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Ge
ben Sie /EHsc an. (..\src\txt_record_buffer_to_object.cpp) [C:\Users\Mathias\Do
cuments\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector
  (688): Bei der Kompilierung der  Klassen-template der std::vector<char,std::a
  llocator<char>>::vector(unsigned __int64)-Memberfunktion
          ..\src\txt_record_buffer_to_object.cpp(26): Siehe Verweis auf die Ins
  tanziierung der gerade kompilierten Funktions-template "std::vector<char,std:
  :allocator<char>>::vector(unsigned __int64)".
          ..\src\txt_record_buffer_to_object.cpp(26): Siehe Verweis auf die Ins
  tanziierung der gerade kompilierten Klassen-template "std::vector<char,std::a
  llocator<char>>".
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\socket_watcher.cpp) [C:\Users\M
athias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\txt_record_ref.cpp) [C:\Users\M
athias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::FunctionTemplate> v8::Per
sistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)" (..\src\t
xt_record_ref.cpp) [C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bi
ndings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\txt_record_set_value.cpp) [C:\U
sers\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\txt_record_get_length.cpp) [C:\
Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\txt_record_deallocate.cpp) [C:\
Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\txt_record_create.cpp) [C:\User
s\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
C:\Users\Mathias\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: Ke
ine Definition für Inlinefunktion "v8::Persistent<v8::Object> v8::Persistent<v8
::Object>::New(v8::Handle<v8::Object>)" (..\src\txt_record_buffer_to_object.cpp
) [C:\Users\Mathias\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
     Bibliothek "C:\Users\Mathias\Documents\GitHub\node_mdns\build\Release\dns_
  sd_bindings.lib" und Objekt "C:\Users\Mathias\Documents\GitHub\node_mdns\buil
  d\Release\dns_sd_bindings.exp" werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  dns_sd_bindings.vcxproj -> C:\Users\Mathias\Documents\GitHub\node_mdns\build\
  Release\\dns_sd_bindings.node

C:\Users\Mathias\Documents\GitHub\node_mdns>
```

**Comment by essingh** [comment]
Thanks mathias. Looks like I should just reinstall VS13/SDK and Bonjour.. I can't for the life of me figure out why I'm missing libs. Anyway, thanks for letting me know that it indeed works on Win 8.1 .

**Comment by agnat** [comment]
@mathiask88, thanks for the heads-up.

Closing this PR. @essingh, feel free to take it back to #113 if you have any news or want to discuss things.

**Pull request closed without merging**
