### PR TITLE
lib: should use ServiceType.prototype.isWildcard

### PR DESCRIPTION
**Pull request by yorkie**
Just make an improvement on function consistence

### CODE REVIEW

**Comment by agnat** [comment]
Thanks.

**Comment by yorkie** [comment]
My pleasure :)

**Comment by agnat** [comment]
Hehe ... unfortunately you didn't test it and it does not actually work:

````
Browser
/Users/david/projects/node.js/node_mdns/lib/service_type.js:50
  var is_wildcard = ServiceType.isWildcard.call(string)
                                          ^

TypeError: Cannot read property 'call' of undefined
    at ServiceType.fromString (/Users/david/projects/node.js/node_mdns/lib/service_type.js:50:43)
    at new ServiceType (/Users/david/projects/node.js/node_mdns/lib/service_type.js:15:14)
    at Object.makeServiceType (/Users/david/projects/node.js/node_mdns/lib/service_type.js:133:10)
    at new Browser (/Users/david/projects/node.js/node_mdns/lib/browser.js:18:27)
    at Function.create (/Users/david/projects/node.js/node_mdns/lib/browser.js:114:10)
    at module.exports.Browser.Should retrieve interface name from cache when interface index is no longer valid (/Users/david/projects/node.js/node_mdns/tests/test_browser.js:45:88)
    at run_testcase (/Users/david/projects/node.js/node_mdns/utils/testrun:191:3)
    at Array.<anonymous> (/Users/david/projects/node.js/node_mdns/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/david/projects/node.js/node_mdns/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/david/projects/node.js/node_mdns/node_modules/slide/lib/chain.js:20:5)
npm ERR! Test failed.  See above for more details.
````

**Comment by yorkie** [comment]
Sorry @agnat :(

**Comment by agnat** [comment]
No worries.

**Pull request merged**
