### PR TITLE
Track the advertisement callback in test file.

### PR DESCRIPTION
**Pull request by KhaosT**
Fix the crash in the functional test. A new variable is added to track the advertisement registration state.

### CODE REVIEW

**Comment by KhaosT** [comment]
@agnat this should fix the crash you experienced.

**Comment by agnat** [comment]
Nope, still the same: :-/

````
test_functional
✔ simple browsing                                       [116/116]
✔ create ads                                            [8/8]
✘ update ad record                                      [7/8]
AssertionError: 'txtRecord' doesn't match
{ [AssertionError: 'txtRecord' doesn't match]
  name: 'AssertionError',
  actual: '1',
  expected: '2',
  operator: '===',
  message: '\'txtRecord\' doesn\'t match',
  generatedMessage: false }
[SKIPPED] write better test for browseThemAll()
✔ browseThemAll()                                       [0/0]
/Users/david/projects/node.js/node_mdns/lib/advertisement.js:74
  dns_sd.DNSServiceUpdateRecord(this.serviceRef, null, 0, txtRecord, 0);
         ^

TypeError: argument 1 must be a DNSServiceRef (sdRef)
    at TypeError (native)
    at Advertisement.updateTXTRecord (/Users/david/projects/node.js/node_mdns/lib/advertisement.js:74:10)
    at null._onTimeout (/Users/david/projects/node.js/node_mdns/tests/test_functional.js:290:12)
    at Timer.listOnTimeout (timers.js:89:15)
````

This is on OS X 10.11.2.

**Comment by KhaosT** [comment]
@agnat interesting, I'm also on OS X 10.11.2. Are you sure the test_functional.js is the latest?

**Comment by agnat** [comment]
Hehe... yes, pretty sure:

````
  // ...
  var registered = false;

  var ad = mdns.createAdvertisement(service_type, port, {name: 'foobar', txtRecord: {value: '1'}}, function(error, service) {
    if (error) t.fail(error);
    if (registered === false) {
      registered = true;
  // ...
````

I added your branch as a remote...

**Comment by KhaosT** [comment]
I'm still having problem to reproduce this issue... Can you add this line
```js
console.log("Env:"+util.inspect(this));
```
at [here](https://github.com/agnat/node_mdns/blob/master/lib/advertisement.js#L73) and post the result?

**Comment by agnat** [comment]
There you go:

````
✘ update ad record                                      [7/8]
AssertionError: 'txtRecord' doesn't match
{ [AssertionError: 'txtRecord' doesn't match]
  name: 'AssertionError',
  actual: '1',
  expected: '2',
  operator: '===',
  message: '\'txtRecord\' doesn\'t match',
  generatedMessage: false }
[SKIPPED] write better test for browseThemAll()
✔ browseThemAll()                                       [0/0]
Env:Advertisement {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _watcherStarted: false,
  serviceRef: null,
  watcher: SocketWatcher { host: [Circular], callback: [Function] } }
/Users/david/projects/node.js/node_mdns/lib/advertisement.js:75
  dns_sd.DNSServiceUpdateRecord(this.serviceRef, null, 0, txtRecord, 0);
         ^

TypeError: argument 1 must be a DNSServiceRef (sdRef)
    at TypeError (native)
    at Advertisement.updateTXTRecord (/Users/david/projects/node.js/node_mdns/lib/advertisement.js:75:10)
    at null._onTimeout (/Users/david/projects/node.js/node_mdns/tests/test_functional.js:290:12)
    at Timer.listOnTimeout (timers.js:89:15)

````

**Comment by KhaosT** [comment]
Commit 3f64bc7 and a4227d6 together should addressed the situation where the test failed because event "serviceChanged" emitted multiple times from the first browser object.

**Comment by agnat** [comment]
Yep, that works. Please squash the commits.

**Comment by KhaosT** [comment]
Sorry for the delay. I squashed the commits :)

**Comment by agnat** [comment]
> Sorry for the delay.

No worries. Dito. ;)

Released as 2.3.0

**Pull request merged**
