### PR TITLE
Fix Nan Integer ambiguity error

### PR DESCRIPTION
**Pull request by acidhax**
Had a problem not being able to compile due to an ambiguous (uint32,int32) function call to Nan's Integer functions.

### CODE REVIEW

**Comment by agnat** [comment]
Uhm, that's... surprising. Thanks for providing a patch.

Since I'm also the author of these parts of Nan I'd really like to understand what's going on. Could you take a minute and provide the exact compiler error and information on your environment (OS, platform, architecture, compiler)?

**Comment by acidhax** [comment]
...\node_modules\nan\nan_new.h(200): error C2668: 'NanIntern::IntegerFactory<v8::Integer>::New' : ambiguous call to overloaded function (..\src\network_interface.cpp) [...\build\dns_sd_bindings.vcxproj]

...\node_modules\nan\nan_new.h(101): could be
'v8::Local<v8::Integer> NanIntern::IntegerFactory<v8::Integer>::New(uint32_t)'

...\node_modules\nan\nan_new.h(100): or
'v8::Local<v8::Integer> NanIntern::IntegerFactory<v8::Integer>::New(int32_t)'


while trying to match the argument list '(NET_IFINDEX)'
..\src\network_interface.cpp(72) : see reference to function template instantiation 'v8::Local<v8::Integer> NanNew<v8::Integer,NET_IFINDEX>(A0)' being compiled with
[
  A0=NET_IFINDEX
]

**Comment by agnat** [comment]
I see. Thanks. VS, x64, `NET_IFINDEX`... _boom_. Got it.

**Comment by agnat** [comment]
Released in v2.2.6.

Thanks again!

**Comment by acidhax** [comment]
Awesome! Glad I could help, and glad it was an extremely easy fix :P

**Pull request merged**
