### PR TITLE
Update nan for io.js 2.x.x compatibility

### PR DESCRIPTION
**Pull request by imyller**
Referencing iojs/io.js#1620

Replaces #126

### CODE REVIEW

**Comment by victorgama** [comment]
:+1:

**Comment by imyller** [comment]
This PR needs attention from the maintainer.
/cc @agnat

**Comment by agnat** [comment]
Released in 2.2.9. Sorry about the delay.

**Comment by victorgama** [comment]
Perfect! Thank you @agnat!

**Comment by imyller** [comment]
Thank you!

**Pull request merged**
